% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 22-Apr-2022 19:03:11
%
% This script assumes these variables are defined:
%
%   index - input data.
clear all;
clc;
load index_Baseline0.mat;
index=[1.988065844	5	42.1
0.852199917	4	13.99987054
1.752421435	6	83.9
3.080050505	6	66.5
3.800992063	1	82.9
4.232743887	3	86.49626815
1.874680879	6	40.30624779
2.067229295	3	43.30737972
1.840904284	6	59.42420337
1.320429485	2	47.90783228
4.28592553	4	105.9993376
3.050842261	4	66.00009032
1.310127731	6	49.10819505
1.392162989	5	37.83212891
2.256386125	6	72.18297584
2.719750996	2	42.9005539
2.35293711	5	65.03840968
2.49371395	4	54.9997742
0.565924565	5	38.92657582
2.156546649	1	68.5186439
6.94856454	6	95.92207265
2.928466557	5	66.46938529
];
x = index';
% x=x([2:4,6],:);
% Create a Self-Organizing Map
dimension1 = 2;
dimension2 = 1;
net = selforgmap([dimension1 dimension2]);
net.trainparam.epochs=500;
% Train the Network
[net,tr] = train(net,x);
view(net)
% Test the Network
y = net(x);
y=y';% View the Network


% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

